# Generated by Django 3.1.3 on 2020-11-09 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_place', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Precio')),
                ('date', models.DateField(verbose_name='Fecha de Compra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop_place.shopplace', verbose_name='Lugar de compra')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Agregue el producto comprado')),
            ],
            options={
                'verbose_name': 'Registro del Producto Comprado',
                'verbose_name_plural': 'Registros de Productos Comprados',
            },
        ),
    ]
