# Generated by Django 3.1.3 on 2020-11-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_place', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la plaza')),
                ('city', models.CharField(max_length=90, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Lugar de Compra',
                'verbose_name_plural': 'Lugares de Compra',
            },
        ),
    ]
